
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author talha
 */
public class ana extends javax.swing.JFrame {

    public Statement st,st_2 =null;
    public Connection c,c_2 =null;
    public ResultSet rs,rs_2=null;
    PreparedStatement ps,ps_2=null;
    
 
    
    /**
     * Creates new form ana
     */
    public ana() {
        initComponents();
        ara();
        ürün_2_sil();
        jLabel3.setVisible(false);
        jMenu1.setEnabled(false);
        jMenu4.setEnabled(false);
        
        if(giris.yetki.equals("Admin"))
        {
            jMenu1.setEnabled(true);
            jMenu4.setEnabled(true);
        }
        else if(giris.yetki.equals("Müdür"))
        {
            jMenu1.setEnabled(true);
        }
        
        //en üstte klasör resmi koymak için bunu yapıyoruz.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mağaza");
        setBounds(new java.awt.Rectangle(300, 80, 0, 0));

        jLabel1.setText("Barkot");
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel1KeyReleased(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel2.setText("Ürüner");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barkod", "Ürün              ", "Adet", "Fiyat", "Toplam "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setMinWidth(66);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(66);
            jTable1.getColumnModel().getColumn(3).setMinWidth(66);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(66);
            jTable1.getColumnModel().getColumn(4).setMinWidth(66);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(66);
        }

        jLabel4.setText("Toplam");

        jButton1.setText("Nakit Satış");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.setText("0.0");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jButton2.setText("İptal Et");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Temizle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Kredi Kartı İle Satış");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Adet");

        jTextField6.setText("1");
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));

        jMenu1.setText("Ürün");

        jMenuItem1.setText("Ürün Ekle");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Ürün Güncelle");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Ürün Sil");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Kullanıcı");

        jMenuItem5.setText("Kullanıcı İşlemleri");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Yardım");

        jMenuItem4.setText("Yardım");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        yardim yardim = new yardim();
        yardim.setVisible(true); //yardım açıldı
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ekle ekle =new ekle();
        ekle.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        degistir degistir =new degistir();
        degistir.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        tüm tüm =new tüm();
        tüm.setVisible(true);
                
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jLabel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1KeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        
        //sec();
        
        DefaultTableModel tablo =(DefaultTableModel) jTable1.getModel();
        String ara=jTextField1.getText();
        String adet=jTextField6.getText();
        int a=0;
        String ürün_2_adet="0";
        int ürün_2_adet_i=0;
        
        int toplam_adet=0; //ürün_2 + gelen adet == ürünler tablosundaki adeti geçiyormu diye konturol yapacam
        try  //xxx
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st=c.createStatement();
            
            String query="select * from ürün_2 where barkod='"+ara+"'";
            rs=st.executeQuery(query);
            while(rs.next())
            {
                ürün_2_adet=rs.getString("adet");
                a=1;
            }
            ürün_2_adet_i=Integer.parseInt(ürün_2_adet);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "ana,barkod okutma,güncellememi ekelmemi belirledigim= xxx","sql bildirimi",-1);
        }
        
        
        String barkod="";
        String ürün ="";
        String tür="";
        String marka="";
        String t_adet="";
        String cins="";
        String toplam="";
        
        
        int adet_i=0;
        int toplam_i=0;
        
        String lira="";
        String kurus="";
        String lira_s="";
        String kurus_s="";
        int lira_i=0;
        int kurus_i=0;
        int yedek=0;
        String fiyat_s="";
        int lira_t_i=0;
        int kurus_t_i=0;
        
        String fiyat_çrp_adet="";
        try
        {
           Class.forName("com.mysql.jdbc.Driver");
           String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
           c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
           st=c.createStatement();
           String query="select * from ürünler where barkod like '"+ara+"'";
           rs=st.executeQuery(query);
           while(rs.next())
           {
               t_adet=rs.getString("adet");
               adet_i=Integer.parseInt(adet);
               toplam_i=Integer.parseInt(t_adet);
               ürün=rs.getString("ürün");
               toplam_adet+=adet_i;
               toplam_adet+=ürün_2_adet_i;
               if(toplam_i>=toplam_adet)           //ürün lerde toplam adetten fazla adet eklemeye çalışma durumu
               {             
               barkod=rs.getString("barkod");
               lira_s=rs.getString("lira");
               kurus_s=rs.getString("kurus");
               tür=rs.getString("tür");
               marka=rs.getString("marka");
               cins=rs.getString("cins");
               //ekle(barkod,ürün,lira_s,kurus_s,tür,marka,adet,cins,t_adet);
               
               lira=lira_s;
               kurus=kurus_s;
               lira_i=Integer.parseInt(lira_s);
               lira_i*=adet_i;
               kurus_i=Integer.parseInt(kurus_s);
               kurus_i*=adet_i;
               if(kurus_i>=100)
               {
                   yedek=kurus_i/100;
                   lira_i+=yedek;
                   kurus_i-=yedek*100;
               }
               fiyat_çrp_adet=lira_i+"."+kurus_i;     // ürün_2 fiyat kısmını hallettim
                   System.out.println("a");
               lira_s="";
               kurus_s="";
               yedek=0;
               
               fiyat_s=jTextField3.getText();
               
               for(int i=0;i<fiyat_s.length();i++)
               {
                   if(fiyat_s.charAt(i)=='.')
                       yedek=1;
                   if(yedek ==0)
                       lira_s+=fiyat_s.charAt(i);
                   else if(yedek ==1 && fiyat_s.charAt(i) !='.')
                       kurus_s+=fiyat_s.charAt(i);
               }
               
                   System.out.println("b");             /////////////////
               lira_t_i=Integer.parseInt(lira_s);
               lira_t_i+=lira_i;
               
                   
               kurus_t_i=Integer.parseInt(kurus_s);
               kurus_t_i+=kurus_i;
                    
               yedek=0;

                   System.out.println("c");
               if(kurus_t_i>=100)
               {
                   yedek=kurus_t_i/100;
                   lira_t_i+=yedek;
                   kurus_t_i-=yedek*100;
               }
               if(kurus_t_i ==0)
                   fiyat_s=lira_t_i+".00";  
               else if(kurus_t_i ==1)
                   fiyat_s=lira_t_i+".01";  
               else if(kurus_t_i ==2)
                   fiyat_s=lira_t_i+".02";   
               else if(kurus_t_i ==3)
                   fiyat_s=lira_t_i+".03";  
               else if(kurus_t_i ==4)
                    fiyat_s=lira_t_i+".04";         
               else if(kurus_t_i ==5)
                   fiyat_s=lira_t_i+".05";  
               else if(kurus_t_i ==6)
                   fiyat_s=lira_t_i+".06";  
               else if(kurus_t_i ==7)
                   fiyat_s=lira_t_i+".07";  
               else if(kurus_t_i ==8)
                   fiyat_s=lira_t_i+".08";               
               else if(kurus_t_i ==9)
                   fiyat_s=lira_t_i+".09";  
               else
               fiyat_s=lira_t_i+"."+kurus_t_i;   
               
                   System.out.println("d");
               if(a==0)
               ekle(barkod,ürün,lira,kurus,tür,marka,adet,cins,t_adet,fiyat_çrp_adet);
               else
                       güncelle(barkod,ürün_2_adet,adet,lira,kurus);
                   System.out.println("e");
               jTextField3.setText(fiyat_s);
               
               jTextField1.setText("");
               jTextField6.setText("1");
               
               jLabel5.setText("");
               }
               else  //stokda ki ürün sayısından fazla ürün sayısı girilme durumu
                   jLabel5.setText(ürün+"'den Stokda: "+t_adet+ " adet bulunmaktadır");
               
          }  //
            ara();////daddsas
            System.out.println("f");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "ANA,coklu da HATA","SQL BİLDİRİM",-1);
        }
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        satıs();  
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        kullanici kullanici =new kullanici();
        kullanici.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        //tuşa basıldıgı an bastıgımı alır
        char al =evt.getKeyChar();
        //sadece 0-9 arası olmayan karakterler buraya girecek
        if(((al < '0') || (al >'9') && al != '\b')) 
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ürün_2_sil();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        kredi_kartı kart=new kredi_kartı();
        kart.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char al=evt.getKeyChar();
        if(((al < '0') || (al > '9') && al != '\b'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String barkod =jLabel3.getText();
        String fiyat_s="";
        String fiyat_t=jTextField3.getText();
        int fiyat_t_l_i=0;
        String fiyat_t_l_s="";
        int fiyat_t_k_i=0;
        String fiyat_t_k_s="";
        int fiyat_s_l_i=0;
        String fiyat_s_l_s="";
        int fiyat_s_k_i=0;
        String fiyat_s_k_s="";
        int yedek=0;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st=c.createStatement();
            String query="select * from ürün_2 where barkod='"+barkod+"'";
            rs=st.executeQuery(query);
            while(rs.next())
            {
                fiyat_s=rs.getString("fiyat_t");
            }
        } 
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "ürün_iptal_zzz","sql bildirimi",-1);
        }
        
        for(int i=0;i<fiyat_t.length();i++)
        {
            if(fiyat_t.charAt(i) == '.')
                yedek=1;
            if(yedek==0)
                fiyat_t_l_s+=fiyat_t.charAt(i);
            else if(yedek ==1 && fiyat_t.charAt(i) !='.')
                fiyat_t_k_s+=fiyat_t.charAt(i);
        }
        fiyat_t_l_i=Integer.parseInt(fiyat_t_l_s);
        fiyat_t_k_i=Integer.parseInt(fiyat_t_k_s);
        
        yedek=0;
        for(int i=0;i<fiyat_s.length();i++)
        {
            if(fiyat_s.charAt(i) == '.')
                yedek=1;
            if(yedek==0)
                fiyat_s_l_s+=fiyat_s.charAt(i);
            else if(yedek ==1 && fiyat_s.charAt(i) !='.')
                fiyat_s_k_s+=fiyat_s.charAt(i);
        }
        fiyat_s_l_i=Integer.parseInt(fiyat_s_l_s);
        fiyat_s_k_i=Integer.parseInt(fiyat_s_k_s);
        
        if(fiyat_s_k_i > fiyat_t_k_i)
        {
            fiyat_t_l_i-=1;
            fiyat_t_k_i+=100;
        }
        
        fiyat_t_l_i-=fiyat_s_l_i;
        fiyat_t_k_i-=fiyat_s_k_i;
        if(fiyat_t_k_i>=100)
        {
            yedek=fiyat_t_k_i/100;
            fiyat_t_l_i+=yedek;
            fiyat_t_k_i-=100*yedek;
        }
        
        if(fiyat_t_k_i ==0)
            fiyat_s=fiyat_t_l_i+".00";  
        else if(fiyat_t_k_i ==1)
            fiyat_s=fiyat_t_l_i+".01";  
        else if(fiyat_t_k_i ==2)
            fiyat_s=fiyat_t_l_i+".02";   
        else if(fiyat_t_k_i ==3)
            fiyat_s=fiyat_t_l_i+".03";  
        else if(fiyat_t_k_i ==4)
            fiyat_s=fiyat_t_l_i+".04";         
        else if(fiyat_t_k_i ==5)
            fiyat_s=fiyat_t_l_i+".05";  
        else if(fiyat_t_k_i ==6)
            fiyat_s=fiyat_t_l_i+".06";  
        else if(fiyat_t_k_i ==7)
            fiyat_s=fiyat_t_l_i+".07";  
        else if(fiyat_t_k_i ==8)
            fiyat_s=fiyat_t_l_i+".08";               
        else if(fiyat_t_k_i ==9)
            fiyat_s=fiyat_t_l_i+".09";  
        else
            fiyat_s=fiyat_t_l_i+"."+fiyat_t_k_i;   
        
        jTextField3.setText(fiyat_s);
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st=c.createStatement();
            String query="delete from ürün_2 where barkod="+barkod;
            ps=c.prepareStatement(query);
            ps.executeUpdate();
            ara();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "ana,iptalde hata","SQL BİLDİRİMİ",-1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        DefaultTableModel tablo =(DefaultTableModel) jTable1.getModel();
        jLabel3.setText(tablo.getValueAt(jTable1.getSelectedRow(), 0).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        
        char al=evt.getKeyChar();
        if(((al < '0') || (al > '9') && al != '\b'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ana().setVisible(true);
            }
        });
    }


    public void ekle(String barkod,String ürün,String lira,String kurus,String tür,String marka,String adet,String cins,String t_adet,String fiyat_s)
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st=c.createStatement();
            String query="insert into ürün_2 (barkod,ürün,lira,kurus,tür,marka,adet,cins,fiyat_t)values('"+barkod+"','"+ürün+"','"+lira+"','"+kurus+"','"+tür+"','"+marka+"','"+adet+"','"+cins+"','"+fiyat_s+"')";
            ps=c.prepareStatement(query);
            ps.executeUpdate();
            ara();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "ürün2 ye ekleme isleminde hata","sql bildirim",-1);
        }
        
    }
    public void güncelle(String barkod,String ürün_2_adet,String adet,String lira,String kurus) //ürün_2 deki adet sayısı(tablodaki adet sayısı),girilen adet sayısı
    {
        int adet_1=Integer.parseInt(ürün_2_adet);
        int adet_2=Integer.parseInt(adet);
        adet_1+=adet_2;
        
        int lira_i=Integer.parseInt(lira);
        lira_i*=adet_1;
        int kurus_i=Integer.parseInt(kurus);
        kurus_i*=adet_1;
        int yedek=0;
        if(kurus_i>=100)
        {
            yedek=kurus_i/100;
            lira_i+=yedek;
            kurus_i-=100*yedek;
        }
        String fiyat=lira_i+"."+kurus_i;
        
        try    //yyy
            {
                Class.forName("com.mysql.jdbc.Driver");
                String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
                c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
                st=c.createStatement();
                String query="update ürün_2 set adet= '"+adet_1+"' ,fiyat_t ='"+fiyat+"' where barkod = '"+barkod+"'";
                ps=c.prepareStatement(query);
                ps.executeUpdate();
               
                ara();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "ana,güncelle hata");
            }
    }
    public void ara()
    {
        DefaultTableModel tablo =(DefaultTableModel) jTable1.getModel();
        int rows =tablo.getRowCount();
        String barkod="";
        String ürün="";
        String adet="";
        String lira="";
        String kurus="";
        String fiyat="";
        String fiyat_s="";

        
        for(int i=rows-1 ;i>=0;i--)
        {
            tablo.removeRow(i);
        }
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st=c.createStatement();
            String query="select * from ürün_2";
            rs=st.executeQuery(query);
            while(rs.next())
            {
                barkod=rs.getString("barkod");
                ürün=rs.getString("ürün");
                adet=rs.getString("adet");
                fiyat_s=rs.getString("fiyat_t"); 
                lira=rs.getString("lira");
                kurus=rs.getString("kurus");
                fiyat=lira+"."+kurus;
                
                
                
                tablo.addRow(new Object[]{barkod,ürün,adet,fiyat,fiyat_s}); 
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "ana,ara butonu hata","SQL BİLDİRİMİ",-1);
        }
    }
        //ürün tablosunda adedi kadar satıs  olan ürünlerin tüketenler tablosuna eklenmesi (ürünler tablosundanda siliyorum bunları)
    public void tükenenler(String barkod,String ürün,String lira,String kurus,String tür,String marka,String alim_tarihi,String cins,String tükenme_tarihi)
    {
        tükenenler_konturol( barkod, tükenme_tarihi);
        
        
        String fiyat=lira+"."+kurus;
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st=c.createStatement();
            
            String query="insert into tüketilenler (barkod,ürün,fiyat,tür,marka,alim_tarihi,tükenme_tarihi,cins) values('"+barkod+"','"+ürün+"','"+fiyat+"','"+tür+"','"+marka+"','"+alim_tarihi+"','"+tükenme_tarihi+"','"+cins+"')";
            ps=c.prepareStatement(query);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "kayıt basarılı","sql bildiirm",-1);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"ana ,tüketilenler hata","SQL BİLDİRİMİ",-1);
        }
    }
    
    public void tükenenler_konturol(String barkod,String tükenme_tarihi)
    {
        int a=0;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c =DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st=c.createStatement();
            
            String query ="select * from tüketilenler where barkod ="+barkod+"";
            rs=st.executeQuery(query);
            while(rs.next())
            {
                a=1;
            }
            if(a==1)
            {
                System.out.println("a");
            }
            System.out.println("b");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "tükenenler_konturol","sql bildirimi",-1);
        }
    }
    
    //sil_2(barkod_2); //ürünler den ürünü sil
    public void sil_2(String barkod_2) //ana tablodan ürünü silme = ürünün bitme durumu   ,ürünler tablosu
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String ulr="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(ulr,database.kullanici_adi,database.parola);
            st=c.createStatement();
            
            String query="delete from ürünler where barkod="+barkod_2;
            ps=c.prepareStatement(query);
            ps.executeUpdate();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "ana sil_2 barkod_2 hata","SQL BİLDİRİMİ",-1);
        }
    }
    public void sil_1(String barkod)   //sepetten ürünü silme islemi  , ürün_2 tablosu  
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st=c.createStatement();
            
            String query="delete from ürün_2 where barkod="+barkod;
            ps=c.prepareStatement(query);
            ps.executeUpdate();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "ana,sil hata","sql bildirimi",-1);
        }
    }
    public void güncelle_2(String adet,String barkod)
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st=c.createStatement();
            
            String query="update ürünler set adet='"+adet+"' where barkod="+barkod;
            ps=c.prepareStatement(query);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "ana,güncelleme işlemi başarılı","sql bildirim",-1);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "ana,güncelleme işlemi hata","sql bildirim",-1);
        }
    }
    public  void satıs()
    {
        String barkod="";
        String barkod_2="";
        String adet="";
        String adet_2="";
        int adet_i=0;
        int adet_i_2=0;
        String ürün="";
        String lira="";
        String kurus="";
        String tür="";
        String marka="";
        String alim_tarihi="";
        String cins="";
        String tükenme_tarihi="";
        
        DateFormat dateFormat =new SimpleDateFormat("dd-MM-yyyy HH-mm-ss");
        Date date =new Date(); //java.util.data =kütüphanesi
        tükenme_tarihi =dateFormat.format(date); //dosyaların alındıgı saati alayımki karısmasınlar =damga
        
        
        DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
        int rows =model.getRowCount(); //count = saymak,row =sıra
        for(int i=rows-1;i>=0;i--) 
        {
            model.removeRow(i);
        }
        
        
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st=c.createStatement();
            String query="select * from ürün_2";
            rs=st.executeQuery(query);
            while(rs.next())                     //xx =ürün_2
            {
                barkod=rs.getString("barkod");
                
                c_2=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
                st_2=c_2.createStatement();
                String query_2="select * from ürünler";
                rs_2=st_2.executeQuery(query_2);
                while(rs_2.next())                 // xx_2 =ürünler
                {
                    barkod_2=rs_2.getString("barkod");
                    if(barkod.equals(barkod_2))
                    {
                        
                        adet=rs.getString("adet");
                        adet_i=Integer.parseInt(adet);
                        
                        adet_2=rs_2.getString("adet");
                        adet_i_2=Integer.parseInt(adet_2);
                        
                        if(adet_i_2 == adet_i) //ürününün stokda bitme durumu
                        {
                            ürün=rs_2.getString("ürün");
                            lira=rs_2.getString("lira");
                            kurus=rs_2.getString("kurus");
                            tür=rs_2.getString("tür");
                            marka=rs_2.getString("marka");
                            alim_tarihi=rs_2.getString("alim_tarih");
                            cins=rs_2.getString("cins");
        
                            tükenenler(barkod_2,ürün,lira,kurus,tür,marka,alim_tarihi,cins,tükenme_tarihi);// ürünler tablosunda(stokda) den ürünün tamamen bitme durumu =tükenenler tablosuna at
                            sil_2(barkod_2); //ürünler den ürünü sil
                            sil_1(barkod);//ürün_2 tablosundan ürünü silme işlemi
                        }
                        else //ürünün stokda tükenmeme durumu
                        {
                            
                            adet_i=adet_i_2-adet_i; //satılan ürün ürünler tablosunda kaçtane kaldıysa günlellemek için kalan adedi buldum
                            adet=String.valueOf(adet_i);
                            güncelle_2(adet,barkod_2);//ürünler tablosunda ürünün yeni sayısını güncelle
                            sil_1(barkod);//ürün_2 tablosundan ürünü silme işlemi
                            JOptionPane.showMessageDialog(null, "else ye girdin","sql bildirimi",-1);
                        }
                    }
                }
            }
            JOptionPane.showMessageDialog(null, "İşlem Başarılı","SQL BİLDİRİMİ",-1);
        }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "ana,satın al hata","SQL BİLDİRİNİ",-1);
        }
        ara();
        jTextField1.setText("");
        jTextField3.setText("0.0");
        jTextField6.setText("1");
    }
    public void ürün_2_sil()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st=c.createStatement();
            String query="delete from ürün_2";
            ps=c.prepareStatement(query);
            ps.executeUpdate();
            ara();
            jTextField3.setText("0.0");
            jTextField1.setText("");
            jTextField6.setText("1");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "ana,silme butonunda hata","sql bilidirimi",-1);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
