
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author talha
 */
public class tüm extends javax.swing.JFrame {
    public Statement st ;
    public Connection c ;
    public ResultSet rs;
    PreparedStatement ps=null;
    
    /**
     * Creates new form tüm
     */
    public tüm() {
        initComponents();
        jLabel2.setVisible(false);
        ara();
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ögrenci_add.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bakkal4");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));

        jLabel1.setText("ürün");

        jButton1.setText("Ara");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barkod", "Ürün", "Adet", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setMinWidth(66);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(66);
            jTable1.getColumnModel().getColumn(3).setMinWidth(66);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(66);
        }

        jButton2.setText("Bütün Ürünler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ara();
        jLabel2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String ara = jTextField1.getText();
        
        DefaultTableModel tablo =(DefaultTableModel) jTable1.getModel();
        int rows =tablo.getRowCount(); //deblo degiskeninde kaç satır oldugunu rows'a yaz
        for(int i = rows-1; i>=0;i--)
        {
            tablo.removeRow(i);//tablonun içindeki indisi sil
        }
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            //String url ="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st= c.createStatement();
          //  String query ="select * from bak where urun like '"+ara+"'";
            String query ="select * from ürünler where ürün like '%"+ara+"%'";
            
            rs =st.executeQuery(query);
            
            while(rs.next())
            {
               String barkodal =rs.getString("barkod");
               String urunal =rs.getString("ürün");
               String liraal =rs.getString("lira");
               String kurusal =rs.getString("kurus");
               String fiyat=liraal+"."+kurusal;
               String adet=rs.getString("adet");
               
               tablo.addRow(new Object[] {barkodal ,urunal ,adet,fiyat});
               
               jLabel2.setText(""); 
                       
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Hata","sql Hatası",-1);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String barkod=jLabel2.getText();
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st=c.createStatement();
            
            String query="delete from ürünler where barkod="+barkod;
            ps=c.prepareStatement(query);
            ps.executeUpdate();
            
            ara();
            jLabel2.setText("");
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null, "tüm,silme islemi hata","sql bildirimi",-1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tablo =(DefaultTableModel) jTable1.getModel();
        jLabel2.setText(tablo.getValueAt(jTable1.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tüm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tüm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tüm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tüm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tüm().setVisible(true);
            }
        });
    }
    public void ara()
    {
        DefaultTableModel tablo =(DefaultTableModel) jTable1.getModel();
        int rows =tablo.getRowCount(); //deblo degiskeninde kaç satır oldugunu rows'a yaz
        for(int i = rows-1; i>=0;i--)
        {
            tablo.removeRow(i);//tablonun içindeki indisi sil
        }
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            //String url ="jdbc:mysql://"+database.host+":"+database.port+"/"+database.database_adı+"?useUnicode=true&characterEncoding=utf8";
            c=DriverManager.getConnection(url,database.kullanici_adi,database.parola);
            st= c.createStatement();
            
            String query ="select * from ürünler";
            
            rs =st.executeQuery(query);
            
            while(rs.next())
            {
               String barkodal =rs.getString("barkod");
               String urunal =rs.getString("ürün");
               String lira =rs.getString("lira");
               String kurus =rs.getString("kurus");
               String fiyat =lira+"."+kurus;
               String adet =rs.getString("adet");
               
               tablo.addRow(new Object[] {barkodal ,urunal ,adet,fiyat});
                       
                       
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Hata","sql Hatası",-1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
